#!/bin/bash

cc src/main.c -framework IOKit -framework Cocoa -framework OpenGL `pkg-config --libs --cflags raylib` -o Bored

echo "********************* FINISHED BUILD *********************"

chmod +x ../Bored
./Bored